### ISSUE TITLE
MTクラウドでmt:assetthumbnailurlが出力されない

### ISSUE THREAD

**Issue by tokiwatch** [tokiwatch/RebuildOncetimePerDay#1]
MTクラウドで実行した際、mt:assetthumbnailurlが処理されず、空になる場合がある。

**Comment by ghost** [comment]
お世話になります。先日メールで問い合わせしました小野村です。
こちらの件、その後いかがでしょうか・・？

**Comment by tokiwatch** [comment]
MTクラウド環境がないので、AWS版で確認をしましたが、特に問題はなく動作しています。
